### ISSUE TITLE
Erro ao abrir link

### ISSUE THREAD

**Issue by O-gait** [mooflu/WebViewPlus#2]
I'm getting an error every time I try to access a link from within the markdown or html file view. The following error " Sorry, browsing not allowed.
"

**Comment by mooflu** [comment]
The plugin isn't meant to be a browser and to be on the safe side it's intentionally not allowed to browse to another location. You can press [Enter](https://github.com/QL-Win/QuickLook?tab=readme-ov-file#hotkeys-and-buttons) in QuickLook (or click the "open with" button at the top) and then continue browsing with a browser or whatever your markdown editor is.
