### ISSUE TITLE
Support for Epub Files

### ISSUE THREAD

**Issue by sidsharths1245** [mooflu/WebViewPlus#3]
Are you planning on adding support for epub files? The default implementation isn't good in QuickLook.

p.s. thank you so much for creating the plugin. This was a life saver especially for password encrypted pdf files. You are the best ❤️

**Comment by mooflu** [comment]
I tried an epub test a while back. See branch https://github.com/mooflu/WebViewPlus/tree/epub-test

I've added it to the main branch yesterday. You can try it here https://mooflu.github.io/WebViewPlus/
It uses epubjs which doesn't seem to be actively being maintained these days and has lots of open issues...

**Comment by sidsharths1245** [comment]
It's working perfectly and I love that I can change the font and the font size. Thank you! :)

**Comment by mooflu** [comment]
I found a few epubs not working well, like being stuck on the cover page and you have to nav to a chapter via table of contents, but hopefully there aren't too many of those. Also couldn't make nav via scroll-wheel work :(

Just published pre-release of 1.5.0 QL plugin with epub: https://github.com/mooflu/QuickLook.Plugin.WebViewPlus/releases/tag/1.5.0

**Comment by sidsharths1245** [comment]
BTW, I found these forks of epubjs which are still being maintained and have more functionalities. I'm adding them here in case you wanna take a look.

https://github.com/intity/epubreader-js
https://github.com/intity/epub-js

**Comment by mooflu** [comment]
Thanks. I'm currently using react-reader which uses the official epubjs under the hood. Another interesting one is foliate-js which supports additional ebook formats like mobi, cbz, etc.
