### ISSUE TITLE
Some Suggestion

### ISSUE THREAD

**Issue by Ignorant12321** [mooflu/WebViewPlus#4]
![image](https://github.com/user-attachments/assets/21b09506-f672-4d08-9eb2-c6d045cb6226)
The plugin will be better, the button can hide .
What's more, it only can preview the online picture( why not support local picture as well ? ).

**Comment by mooflu** [comment]
> The plugin will be better, the button can hide .

I'll change it so they'll hide after a few seconds. 

> What's more, it only can preview the online picture( why not support local picture as well ? ).

For security reasons. The preview occurs in the browser and local files other than the one being previewed are not accessible.

**Comment by mooflu** [comment]
The first part is in 1.5.0
